./output.py /home/isabel/IPC-2018-Files/ipcResults/barman.csv barman.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/barmanlearning11.csv barmanlearning11.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/blocksworldlearning11.csv blocksworldlearning11.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/cybersec-strips.csv cybersec-strips.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/depotslearning11.csv depotslearning11.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/elevators08.csv elevators08.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/elevators.csv elevators.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/floortile.csv floortile.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/gold-minerlearning08.csv gold-minerlearning08.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/gripperlearning11.csv gripperlearning11.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/matching-bwlearning08.csv matching-bwlearning08.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/nomystery.csv nomystery.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/n-puzzlelearning08.csv n-puzzlelearning08.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/openstacks06.csv openstacks06.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/openstacks-adl08.csv openstacks-adl08.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/openstacks.csv openstacks.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/openstacks-strips08.csv openstacks-strips08.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/parcprinter.csv parcprinter.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/parcprinter-strips08.csv parcprinter-strips08.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/parking.csv parking.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/parkinglearning08.csv parkinglearning08.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/parkinglearning11.csv parkinglearning11.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/pathways06.csv pathways06.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/pegsol.csv pegsol.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/pegsol-strips08.csv pegsol-strips08.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/pipesworld06.csv pipesworld06.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/roverlearning11.csv roverlearning11.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/rovers06.csv rovers06.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/satellitelearning11.csv satellitelearning11.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/scanalyzer.csv scanalyzer.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/scanalyzer-strips08.csv scanalyzer-strips08.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/sokoban.csv sokoban.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/sokobanlearning08.csv sokobanlearning08.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/sokoban-strips08.csv sokoban-strips08.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/storage06.csv storage06.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/thoughtfullearning08.csv thoughtfullearning08.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/tidybot.csv tidybot.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/tpp06.csv tpp06.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/tppLearning11.csv tppLearning11.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/trainingphase.csv trainingphase.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/transport.csv transport.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/transport-strips08.csv transport-strips08.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/trucks06.csv trucks06.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/visitall.csv visitall.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/woodworking.csv woodworking.csv
./output.py /home/isabel/IPC-2018-Files/ipcResults/woodworking-strips08.csv woodworking-strips08.csv

