mkdir ArffDomains
./join2FilePlanners.py Arff-nohead/allfeatures-barman.arff csvFiles/barman.csv ArffDomains/barman.arff
./join2FilePlanners.py Arff-nohead/allfeatures-barmanlearning11.arff csvFiles/barmanlearning11.csv ArffDomains/barmanlearning11.arff
./join2FilePlanners.py Arff-nohead/allfeatures-blocksworldlearning11.arff csvFiles/blocksworldlearning11.csv ArffDomains/blocksworldlearning11.arff
./join2FilePlanners.py Arff-nohead/allfeatures-cybersec-strips.arff csvFiles/cybersec-strips.csv ArffDomains/cybersec-strips.arff
./join2FilePlanners.py Arff-nohead/allfeatures-depotslearning11.arff csvFiles/depotslearning11.csv ArffDomains/depotslearning11.arff
./join2FilePlanners.py Arff-nohead/allfeatures-elevators08.arff csvFiles/elevators08.csv ArffDomains/elevators08.arff
./join2FilePlanners.py Arff-nohead/allfeatures-elevators.arff csvFiles/elevators.csv ArffDomains/elevators.arff
./join2FilePlanners.py Arff-nohead/allfeatures-floortile.arff csvFiles/floortile.csv ArffDomains/floortile.arff
./join2FilePlanners.py Arff-nohead/allfeatures-gold-minerlearning08.arff csvFiles/gold-minerlearning08.csv ArffDomains/gold-minerlearning08.arff
./join2FilePlanners.py Arff-nohead/allfeatures-gripperlearning11.arff csvFiles/gripperlearning11.csv ArffDomains/gripperlearning11.arff
./join2FilePlanners.py Arff-nohead/allfeatures-matching-bwlearning08.arff csvFiles/matching-bwlearning08.csv ArffDomains/matching-bwlearning08.arff
./join2FilePlanners.py Arff-nohead/allfeatures-nomystery.arff csvFiles/nomystery.csv ArffDomains/nomystery.arff
./join2FilePlanners.py Arff-nohead/allfeatures-n-puzzlelearning08.arff csvFiles/n-puzzlelearning08.csv ArffDomains/n-puzzlelearning08.arff
./join2FilePlanners.py Arff-nohead/allfeatures-openstacks06.arff csvFiles/openstacks06.csv ArffDomains/openstacks06.arff
./join2FilePlanners.py Arff-nohead/allfeatures-openstacks-adl08.arff csvFiles/openstacks-adl08.csv ArffDomains/openstacks-adl08.arff
./join2FilePlanners.py Arff-nohead/allfeatures-openstacks.arff csvFiles/openstacks.csv ArffDomains/openstacks.arff
./join2FilePlanners.py Arff-nohead/allfeatures-openstacks-strips08.arff csvFiles/openstacks-strips08.csv ArffDomains/openstacks-strips08.arff
./join2FilePlanners.py Arff-nohead/allfeatures-parcprinter.arff csvFiles/parcprinter.csv ArffDomains/parcprinter.arff
./join2FilePlanners.py Arff-nohead/allfeatures-parcprinter-strips08.arff csvFiles/parcprinter-strips08.csv ArffDomains/parcprinter-strips08.arff
./join2FilePlanners.py Arff-nohead/allfeatures-parking.arff csvFiles/parking.csv ArffDomains/parking.arff
./join2FilePlanners.py Arff-nohead/allfeatures-parkinglearning08.arff csvFiles/parkinglearning08.csv ArffDomains/parkinglearning08.arff
./join2FilePlanners.py Arff-nohead/allfeatures-parkinglearning11.arff csvFiles/parkinglearning11.csv ArffDomains/parkinglearning11.arff
./join2FilePlanners.py Arff-nohead/allfeatures-pathways06.arff csvFiles/pathways06.csv ArffDomains/pathways06.arff
./join2FilePlanners.py Arff-nohead/allfeatures-pegsol.arff csvFiles/pegsol.csv ArffDomains/pegsol.arff
./join2FilePlanners.py Arff-nohead/allfeatures-pegsol-strips08.arff csvFiles/pegsol-strips08.csv ArffDomains/pegsol-strips08.arff
./join2FilePlanners.py Arff-nohead/allfeatures-pipesworld06.arff csvFiles/pipesworld06.csv ArffDomains/pipesworld06.arff
./join2FilePlanners.py Arff-nohead/allfeatures-roverlearning11.arff csvFiles/roverlearning11.csv ArffDomains/roverlearning11.arff
./join2FilePlanners.py Arff-nohead/allfeatures-rovers06.arff csvFiles/rovers06.csv ArffDomains/rovers06.arff
./join2FilePlanners.py Arff-nohead/allfeatures-satellitelearning11.arff csvFiles/satellitelearning11.csv ArffDomains/satellitelearning11.arff
./join2FilePlanners.py Arff-nohead/allfeatures-scanalyzer.arff csvFiles/scanalyzer.csv ArffDomains/scanalyzer.arff
./join2FilePlanners.py Arff-nohead/allfeatures-scanalyzer-strips08.arff csvFiles/scanalyzer-strips08.csv ArffDomains/scanalyzer-strips08.arff
./join2FilePlanners.py Arff-nohead/allfeatures-sokoban.arff csvFiles/sokoban.csv ArffDomains/sokoban.arff
./join2FilePlanners.py Arff-nohead/allfeatures-sokobanlearning08.arff csvFiles/sokobanlearning08.csv ArffDomains/sokobanlearning08.arff
./join2FilePlanners.py Arff-nohead/allfeatures-sokoban-strips08.arff csvFiles/sokoban-strips08.csv ArffDomains/sokoban-strips08.arff
./join2FilePlanners.py Arff-nohead/allfeatures-spannerlearning11.arff csvFiles/storage06.csv ArffDomains/storage06.arff
./join2FilePlanners.py Arff-nohead/allfeatures-storage06.arff csvFiles/thoughtfullearning08.csv ArffDomains/thoughtfullearning08.arff
./join2FilePlanners.py Arff-nohead/allfeatures-thoughtfullearning08.arff csvFiles/tidybot.csv ArffDomains/tidybot.arff
./join2FilePlanners.py Arff-nohead/allfeatures-tidybot.arff csvFiles/tpp06.csv ArffDomains/tpp06.arff
./join2FilePlanners.py Arff-nohead/allfeatures-tpp06.arff csvFiles/tppLearning11.csv ArffDomains/tppLearning11.arff
./join2FilePlanners.py Arff-nohead/allfeatures-tppLearning11.arff csvFiles/trainingphase.csv ArffDomains/trainingphase.arff
./join2FilePlanners.py Arff-nohead/allfeatures-transport.arff csvFiles/transport.csv ArffDomains/transport.arff
./join2FilePlanners.py Arff-nohead/allfeatures-transport-strips08.arff csvFiles/transport-strips08.csv ArffDomains/transport-strips08.arff
./join2FilePlanners.py Arff-nohead/allfeatures-trucks06.arff csvFiles/trucks06.csv ArffDomains/trucks06.arff
./join2FilePlanners.py Arff-nohead/allfeatures-visitall.arff csvFiles/visitall.csv ArffDomains/visitall.arff
./join2FilePlanners.py Arff-nohead/allfeatures-woodworking.arff csvFiles/woodworking.csv ArffDomains/woodworking.arff
./join2FilePlanners.py Arff-nohead/allfeatures-woodworking-strips08.arff csvFiles/woodworking-strips08.csv ArffDomains/woodworking-strips08.arff

