cat ArffDomains-nohead/barman.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/barmanlearning11.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/blocksworldlearning11.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/cybersec-strips.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/depotslearning11.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/elevators08.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/elevators.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/floortile.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/gold-minerlearning08.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/gripperlearning11.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/matching-bwlearning08.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/nomystery.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/n-puzzlelearning08.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/openstacks06.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/openstacks-adl08.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/openstacks.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/openstacks-strips08.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/parcprinter.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/parcprinter-strips08.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/parking.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/parkinglearning08.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/parkinglearning11.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/pathways06.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/pegsol.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/pegsol-strips08.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/pipesworld06.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/roverlearning11.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/rovers06.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/satellitelearning11.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/scanalyzer.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/scanalyzer-strips08.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/sokoban.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/sokobanlearning08.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/sokoban-strips08.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/storage06.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/thoughtfullearning08.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/tidybot.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/tpp06.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/tppLearning11.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/transport.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/transport-strips08.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/trucks06.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/visitall.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/woodworking.arff >> finalNewPlanners.arff
cat ArffDomains-nohead/woodworking-strips08.arff >> finalNewPlanners.arff

