./output.py ipcResults/barman.csv csvFiles/barman.csv
./output.py ipcResults/barmanlearning11.csv csvFiles/barmanlearning11.csv
./output.py ipcResults/blocksworldlearning11.csv csvFiles/blocksworldlearning11.csv
./output.py ipcResults/cybersec-strips.csv csvFiles/cybersec-strips.csv
./output.py ipcResults/depotslearning11.csv csvFiles/depotslearning11.csv
./output.py ipcResults/elevators08.csv csvFiles/elevators08.csv
./output.py ipcResults/elevators.csv csvFiles/elevators.csv
./output.py ipcResults/floortile.csv csvFiles/floortile.csv
./output.py ipcResults/gold-minerlearning08.csv csvFiles/gold-minerlearning08.csv
./output.py ipcResults/gripperlearning11.csv csvFiles/gripperlearning11.csv
./output.py ipcResults/matching-bwlearning08.csv csvFiles/matching-bwlearning08.csv
./output.py ipcResults/nomystery.csv csvFiles/nomystery.csv
./output.py ipcResults/n-puzzlelearning08.csv csvFiles/n-puzzlelearning08.csv
./output.py ipcResults/openstacks06.csv csvFiles/openstacks06.csv
./output.py ipcResults/openstacks-adl08.csv csvFiles/openstacks-adl08.csv
./output.py ipcResults/openstacks.csv csvFiles/openstacks.csv
./output.py ipcResults/openstacks-strips08.csv csvFiles/openstacks-strips08.csv
./output.py ipcResults/parcprinter.csv csvFiles/parcprinter.csv
./output.py ipcResults/parcprinter-strips08.csv csvFiles/parcprinter-strips08.csv
./output.py ipcResults/parking.csv csvFiles/parking.csv
./output.py ipcResults/parkinglearning08.csv csvFiles/parkinglearning08.csv
./output.py ipcResults/parkinglearning11.csv csvFiles/parkinglearning11.csv
./output.py ipcResults/pathways06.csv csvFiles/pathways06.csv
./output.py ipcResults/pegsol.csv csvFiles/pegsol.csv
./output.py ipcResults/pegsol-strips08.csv csvFiles/pegsol-strips08.csv
./output.py ipcResults/pipesworld06.csv csvFiles/pipesworld06.csv
./output.py ipcResults/roverlearning11.csv csvFiles/roverlearning11.csv
./output.py ipcResults/rovers06.csv csvFiles/rovers06.csv
./output.py ipcResults/satellitelearning11.csv csvFiles/satellitelearning11.csv
./output.py ipcResults/scanalyzer.csv csvFiles/scanalyzer.csv
./output.py ipcResults/scanalyzer-strips08.csv csvFiles/scanalyzer-strips08.csv
./output.py ipcResults/sokoban.csv csvFiles/sokoban.csv
./output.py ipcResults/sokobanlearning08.csv csvFiles/sokobanlearning08.csv
./output.py ipcResults/sokoban-strips08.csv csvFiles/sokoban-strips08.csv
./output.py ipcResults/storage06.csv csvFiles/storage06.csv
./output.py ipcResults/thoughtfullearning08.csv csvFiles/thoughtfullearning08.csv
./output.py ipcResults/tidybot.csv csvFiles/tidybot.csv
./output.py ipcResults/tpp06.csv csvFiles/tpp06.csv
./output.py ipcResults/tppLearning11.csv csvFiles/tppLearning11.csv
./output.py ipcResults/trainingphase.csv csvFiles/trainingphase.csv
./output.py ipcResults/transport.csv csvFiles/transport.csv
./output.py ipcResults/transport-strips08.csv csvFiles/transport-strips08.csv
./output.py ipcResults/trucks06.csv csvFiles/trucks06.csv
./output.py ipcResults/visitall.csv csvFiles/visitall.csv
./output.py ipcResults/woodworking.csv csvFiles/woodworking.csv
./output.py ipcResults/woodworking-strips08.csv csvFiles/woodworking-strips08.csv

