./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain barman > barman.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain barmanlearning11 > barmanlearning11.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain blocksworldlearning11 > blocksworldlearning11.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain cybersec-strips > cybersec-strips.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain depotslearning11 > depotslearning11.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain elevators > elevators.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain elevators08 > elevators08.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain floortile > floortile.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain gold-minerlearning08 > gold-minerlearning08.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain gripperlearning11 > gripperlearning11.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain matching-bwlearning08 > matching-bwlearning08.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain nomystery > nomystery.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain n-puzzlelearning08 > n-puzzlelearning08.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain openstacks > openstacks.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain openstacks06 > openstacks06.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain openstacks-adl08 > openstacks-adl08.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain openstacks-strips08 > openstacks-strips08.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain parcprinter > parcprinter.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain parcprinter-strips08 > parcprinter-strips08.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain parking > parking.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain parkinglearning08 > parkinglearning08.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain parkinglearning11 > parkinglearning11.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain pathways06 > pathways06.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain pegsol > pegsol.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain pegsol-strips08 > pegsol-strips08.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain pipesworld06 > pipesworld06.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain roverlearning11 > roverlearning11.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain rovers06 > rovers06.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain satellitelearning11 > satellitelearning11.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain scanalyzer > scanalyzer.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain scanalyzer-strips08 > scanalyzer-strips08.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain sokoban > sokoban.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain sokobanlearning08 > sokobanlearning08.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain sokoban-strips08 > sokoban-strips08.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain storage06 > storage06.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain thoughtfullearning08 > thoughtfullearning08.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain tidybot > tidybot.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain tpp06 > tpp06.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain tppLearning11 > tppLearning11.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain trainingphase > trainingphase.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain transport > transport.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain transport-strips08 > transport-strips08.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain trucks06 > trucks06.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain visitall > visitall.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain woodworking > woodworking.csv
./report.py --directory /home/isabel/Desktop/newResults/results/seq-sat/ --variable oktimefirstsol --ascending domain --domain woodworking-strips08 > woodworking-strips08.csv

