
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/barmanlearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/depotslearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/gold-minerlearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/matching-bwlearning08/
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/puzzlelearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/openstacks06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/parkinglearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/parkinglearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/pathways06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/pipesworld06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/roverlearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/rovers06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/sokobanlearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/storage06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/thoughtfullearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/tidybot
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/tpp06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/tppLearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/trucks06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/bfs-f/visitall
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/barmanlearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/blocksworldlearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/depotslearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/gold-minerlearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/gripperlearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/matching-bwlearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/n-puzzlelearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/openstacks06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/parkinglearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/parkinglearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/pathways06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/pipesworld06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/roverlearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/rovers06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/sokobanlearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/storage06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/tidybot
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/tpp06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/tppLearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/trucks06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/jasper/visitall
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/barmanlearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/blocksworldlearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/depotslearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/gold-minerlearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/gripperlearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/matching-bwlearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/n-puzzlelearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/openstacks06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/parkinglearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/parkinglearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/pathways06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/pipesworld06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/roverlearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/rovers06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/sokobanlearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/storage06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/tidybot
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/tpp06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/tppLearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/trucks06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/mercury/visitall
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/barmanlearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/blocksworldlearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/depotslearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/gold-minerlearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/gripperlearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/matching-bwlearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/n-puzzlelearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/openstacks06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/parkinglearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/parkinglearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/pathways06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/pipesworld06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/roverlearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/rovers06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/sokobanlearning08
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/storage06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/tidybot
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/tpp06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/tppLearning11
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/trucks06
./runValidateIsa.sh /home/isabel/Desktop/newResults/results/seq-sat/siw/visitall
./runValidateIsa.sh 
